package database;
// Generated 24 ene 2022 11:02:28 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments implements java.io.Serializable {

	private Integer departmentId;
	private Locations locations;
	private String departmentName;
	private Set employeeses = new HashSet(0);

	public Departments() {
	}

	public Departments(String departmentName) {
		this.departmentName = departmentName;
	}

	public Departments(Locations locations, String departmentName, Set employeeses) {
		this.locations = locations;
		this.departmentName = departmentName;
		this.employeeses = employeeses;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public Set getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set employeeses) {
		this.employeeses = employeeses;
	}

}
