package database;
// Generated 24 ene 2022 11:02:28 by Hibernate Tools 5.5.7.Final

/**
 * Dependents generated by hbm2java
 */
public class Dependents implements java.io.Serializable {

	private Integer dependentId;
	private Employees employees;
	private String firstName;
	private String lastName;
	private String relationship;

	public Dependents() {
	}

	public Dependents(Employees employees, String firstName, String lastName, String relationship) {
		this.employees = employees;
		this.firstName = firstName;
		this.lastName = lastName;
		this.relationship = relationship;
	}

	public Integer getDependentId() {
		return this.dependentId;
	}

	public void setDependentId(Integer dependentId) {
		this.dependentId = dependentId;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

}
