package database;
// Generated 24 ene 2022 11:02:28 by Hibernate Tools 5.5.7.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs implements java.io.Serializable {

	private Integer jobId;
	private String jobTitle;
	private BigDecimal minSalary;
	private BigDecimal maxSalary;
	private Set employeeses = new HashSet(0);

	public Jobs() {
	}

	public Jobs(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public Jobs(String jobTitle, BigDecimal minSalary, BigDecimal maxSalary, Set employeeses) {
		this.jobTitle = jobTitle;
		this.minSalary = minSalary;
		this.maxSalary = maxSalary;
		this.employeeses = employeeses;
	}

	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public BigDecimal getMinSalary() {
		return this.minSalary;
	}

	public void setMinSalary(BigDecimal minSalary) {
		this.minSalary = minSalary;
	}

	public BigDecimal getMaxSalary() {
		return this.maxSalary;
	}

	public void setMaxSalary(BigDecimal maxSalary) {
		this.maxSalary = maxSalary;
	}

	public Set getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set employeeses) {
		this.employeeses = employeeses;
	}

}
