package database;
// Generated 24 ene 2022 11:02:28 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Regions generated by hbm2java
 */
public class Regions implements java.io.Serializable {

	private Integer regionId;
	private String regionName;
	private Set countrieses = new HashSet(0);

	public Regions() {
	}

	public Regions(String regionName, Set countrieses) {
		this.regionName = regionName;
		this.countrieses = countrieses;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public Set getCountrieses() {
		return this.countrieses;
	}

	public void setCountrieses(Set countrieses) {
		this.countrieses = countrieses;
	}

}
