package database;
// Generated 19 feb 2022 18:47:50 by Hibernate Tools 5.5.7.Final

/**
 * CountryLanguagesId generated by hbm2java
 */
public class CountryLanguagesId implements java.io.Serializable {

	private int countryId;
	private int languageId;

	public CountryLanguagesId() {
	}

	public CountryLanguagesId(int countryId, int languageId) {
		this.countryId = countryId;
		this.languageId = languageId;
	}

	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CountryLanguagesId))
			return false;
		CountryLanguagesId castOther = (CountryLanguagesId) other;

		return (this.getCountryId() == castOther.getCountryId()) && (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCountryId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
