package database;
// Generated 28 ene 2022 12:58:48 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Continents generated by hbm2java
 */
public class Continents implements java.io.Serializable {

	private Integer continentId;
	private String name;
	private Set regionses = new HashSet(0);

	public Continents() {
	}

	public Continents(String name) {
		this.name = name;
	}

	public Continents(String name, Set regionses) {
		this.name = name;
		this.regionses = regionses;
	}

	public Integer getContinentId() {
		return this.continentId;
	}

	public void setContinentId(Integer continentId) {
		this.continentId = continentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getRegionses() {
		return this.regionses;
	}

	public void setRegionses(Set regionses) {
		this.regionses = regionses;
	}

}
