package database;
// Generated 28 ene 2022 12:58:48 by Hibernate Tools 5.5.7.Final

/**
 * CountryStats generated by hbm2java
 */
public class CountryStats implements java.io.Serializable {

	private CountryStatsId id;
	private Countries countries;
	private Integer population;
	private Long gdp;

	public CountryStats() {
	}

	public CountryStats(CountryStatsId id, Countries countries) {
		this.id = id;
		this.countries = countries;
	}

	public CountryStats(CountryStatsId id, Countries countries, Integer population, Long gdp) {
		this.id = id;
		this.countries = countries;
		this.population = population;
		this.gdp = gdp;
	}

	public CountryStatsId getId() {
		return this.id;
	}

	public void setId(CountryStatsId id) {
		this.id = id;
	}

	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	public Integer getPopulation() {
		return this.population;
	}

	public void setPopulation(Integer population) {
		this.population = population;
	}

	public Long getGdp() {
		return this.gdp;
	}

	public void setGdp(Long gdp) {
		this.gdp = gdp;
	}

}
