package database;
// Generated 28 ene 2022 12:58:48 by Hibernate Tools 5.5.7.Final

/**
 * CountryLanguages generated by hbm2java
 */
public class CountryLanguages implements java.io.Serializable {

	private CountryLanguagesId id;
	private Countries countries;
	private Languages languages;
	private boolean official;

	public CountryLanguages() {
	}

	public CountryLanguages(CountryLanguagesId id, Countries countries, Languages languages, boolean official) {
		this.id = id;
		this.countries = countries;
		this.languages = languages;
		this.official = official;
	}

	public CountryLanguagesId getId() {
		return this.id;
	}

	public void setId(CountryLanguagesId id) {
		this.id = id;
	}

	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	public Languages getLanguages() {
		return this.languages;
	}

	public void setLanguages(Languages languages) {
		this.languages = languages;
	}

	public boolean isOfficial() {
		return this.official;
	}

	public void setOfficial(boolean official) {
		this.official = official;
	}

}
