package database;
// Generated 28 ene 2022 12:58:48 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Regions generated by hbm2java
 */
public class Regions implements java.io.Serializable {

	private Integer regionId;
	private Continents continents;
	private String name;
	private Set countrieses = new HashSet(0);

	public Regions() {
	}

	public Regions(Continents continents, String name) {
		this.continents = continents;
		this.name = name;
	}

	public Regions(Continents continents, String name, Set countrieses) {
		this.continents = continents;
		this.name = name;
		this.countrieses = countrieses;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	public Continents getContinents() {
		return this.continents;
	}

	public void setContinents(Continents continents) {
		this.continents = continents;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCountrieses() {
		return this.countrieses;
	}

	public void setCountrieses(Set countrieses) {
		this.countrieses = countrieses;
	}

}
