package database;
// Generated 16 feb 2022 16:50:26 by Hibernate Tools 5.5.7.Final

/**
 * CountryStatsId generated by hbm2java
 */
public class CountryStatsId implements java.io.Serializable {

	private int countryId;
	private int year;

	public CountryStatsId() {
	}

	public CountryStatsId(int countryId, int year) {
		this.countryId = countryId;
		this.year = year;
	}

	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CountryStatsId))
			return false;
		CountryStatsId castOther = (CountryStatsId) other;

		return (this.getCountryId() == castOther.getCountryId()) && (this.getYear() == castOther.getYear());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCountryId();
		result = 37 * result + this.getYear();
		return result;
	}

}
